aiverify-foundation/moonshot

src/moonshot/data/metrics/factscore.py
src/moonshot/src/benchmarking/metrics.py

add metrics to metrics_cache 
update logger inputs

fix loading metrics consuming memory

---

web_api/routes/redteam.py
web_api/services/session_service.py

Also updated the select_prompt_template in session_services.
set_active_session() is unmodified as there is no longer a use for it.
unset_prompt_template is unmodified as I don't think there is a need for since we can use set_prompt_template and pass in an empty string as the value.

Add exception to catch error in redteam routes.

---

moonshot/src/storage/storage_manager.py

update delete files will raise exception when not found or unable to delete. else it will be successful

MS-116 Fix deletion on non-exist files, raise exception

---

moonshot/api.py
moonshot/src/benchmarking/cookbooks/cookbook.py
moonshot/src/benchmarking/recipes/recipe.py
moonshot/src/connectors/connector_manager.py
tests/test_api.py

fix update for recipe, cookbook and endpoints based on id and values

MS-117 fix recipe, cookbook and endpoint update API

---

moonshot/integrations/web_api/routes/benchmark.py
moonshot/integrations/web_api/schemas/session_response_model.py
moonshot/integrations/web_api/services/session_service.py

get all results on separate route

separate route for get all results

---

README.md
docs/getting_started/installation.md
docs/web_api/web_api_guide.md
moonshot/__main__.py
pyproject.toml

* modify docs and readme
* add back dependency
* fix typo
---------

modify docs and readme (#63)

---

moonshot/data/prompt-templates/bbq-template.json
moonshot/data/prompt-templates/cbbq-template.json
moonshot/data/prompt-templates/coqa-conversational-qna.json
moonshot/data/prompt-templates/gsm8k-template1.json
moonshot/data/prompt-templates/legal-term-template.json
moonshot/data/prompt-templates/real-toxicity-prompt-template1.json
moonshot/data/prompt-templates/real-toxicity-prompt-template2.json

update prompt templates name

---

moonshot/src/prompt_template/prompt_template_manager.py

* removed context strategy class for now
* removed test_api.py
* updated open with utf8 for file opening

Ms 115 (#69)

---

moonshot/integrations/web_api/services/benchmark_test_manager.py

Now that executor.execute can be awaited, web_api module can go async all the way in the same thread even for executing benchmarks.
Unfortunately, this approach will still need to be changed to using processes, for cancelling feature. This is being done in separate branch. Merging this one first so that running benchmarks on from web_api is not broken

update calling of executor.execute and removal of threaded approach in web_api

---

moonshot/integrations/cli/benchmark/cookbook.py
moonshot/integrations/cli/benchmark/recipe.py
moonshot/integrations/cli/benchmark/results.py
moonshot/integrations/cli/benchmark/run.py
moonshot/integrations/cli/common/connectors.py
moonshot/src/cookbooks/cookbook.py
moonshot/src/recipes/recipe.py
moonshot/src/runners/runner.py
moonshot/src/runs/run.py
moonshot/src/runs/run_arguments.py

1. Update benchmark and common functions.
2. Catch exceptions and return as a message
3. Update cookbook and recipe to include displaying type and attack strategies.
4. Update update functions to display the keys available in help message.
5. Modify run_recipe / run_cookbook to allow running the same name. If the file exist, it will load and run as a new run, if the file dont exist it will just create a new runner and run.
6. Added code to get the latest run information for displaying of results for runs

ms-142 update cli

---

moonshot/data/metrics/advglue.py
moonshot/data/metrics/bertscore.py
moonshot/data/metrics/bleuscore.py
moonshot/data/metrics/exactstrmatch.py
moonshot/data/metrics/exactstrmultimatch.py
moonshot/data/metrics/leakagerate.py
moonshot/data/metrics/readabilityscore.py
moonshot/data/metrics/relaxstrmatch.py
moonshot/data/metrics/reverseexactstrmatch.py
moonshot/data/metrics/rougescore.py
moonshot/data/metrics/rougescorer.py
moonshot/data/metrics/spelling.py
moonshot/data/metrics/toxicity-classifier.py
moonshot/data/reports-analysis-modules/results-comparator.py
moonshot/src/metrics/metric_interface.py
moonshot/src/report_analysis/report_analysis_interface.py

remove json validation

---

moonshot/integrations/web_api/status_updater/moonshot_ui_webhook.py

update art webhook url

---

docs/getting_started/installation.md
docs/getting_started/walkthrough.md
mkdocs.yml

Add tabs for creation of virtual environment in installation guide

Add tabs for Installation Guide

---

docs/contributing.md
docs/getting_started/first_test.md
docs/getting_started/overview.md
docs/index.md
docs/tutorial/cli/create_benchmark_tests.md
docs/tutorial/cli/create_endpoint.md
docs/tutorial/cli/run_benchmark_tests.md
docs/tutorial/cli/run_red_teaming.md
docs/tutorial/web-ui/benchmark.md
docs/tutorial/web-ui/redteam.md
docs/user_guide/web_ui/moonshot_interface/redteaming.md
docs/user_guide/web_ui/moonshot_interface/utils.md
docs/user_guide/web_ui/running_red_teaming.md

For your review @imda-normanchia. Thank you!

Proofreading of documentation Round 1

---

README.md

Updated the link for README

---

README.md

Updated two links.

---

.pre-commit-config.yaml

Code changes enables 
- Detect hardcorded secrets before committing.
Planned chore
- chore: Routine tasks, maintenance, or tooling changes
Add the following code to simulate an openai key
`my_redacted_token = "sk-proj-123456789T123456789T123456789m123456789m1234567"`
If there is no leaked key, it will show PASSED.
<details>
```
Version 1.1
Developer's …
```

[MS-261] Detect hardcoded secrets

---

.github/workflows/sca_scan.yaml

Add Blackduck Scanning On Pull Request & Work Dispatch
To enable Vulnerabilities & License Scans On Pull Request & Work Dispatch
Run Blackduck Scanning Workflow On Pull Request & Work Dispatch
<details>
```
Version 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it …
```

Add Software Composition Analysis Scan

---

.github/workflows/smoke-test.yaml

Add Smoke Test Workflow for All PRs
Add Smoke Test Workflow for All PRs
<details>
```
Version 1.1
By making a contribution to this project, I certify that:
(a) The contribution was …
```

Add Smoke Test Workflow

---

moonshot/integrations/cli/redteam/session.py

Updated bookmark in CLI
Updated bookmark in CLI
Code style changes (e.g., formatting, indentation) 
<details>
```
Version 1.1
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in …
```

updated context strategy and number of prompts in CLI

---

moonshot/integrations/web_api/schemas/recipe_create_dto.py
moonshot/integrations/web_api/services/recipe_service.py
tests/unit-tests/src/test_api_bookmark.py
tests/unit-tests/src/test_api_dataset.py
tests/unit-tests/web_api/test_routes/test_routes_recipe.py
tests/unit-tests/web_api/test_services/test_service_recipe.py

<details>
```
Version 1.1
Everyone …
```

Fix web api test

---

pyproject.toml

<details>
```
Version 1.1
Everyone …
```

add missing dependency

---

.github/workflows/smoke-test.yaml

<details>
```
Version 1.1
Copyright (C) 2004, 2006 …
```

Change Executed Test Script For Smoke Test

---

moonshot/integrations/web_api/routes/bookmark.py

Update the current export bookmark web-api endpoint to return File Response instead of just the filepath
This is for a new feature where user can download the saved bookmarks as json file from the UI
- feat: A new feature
- [x ]  I have tested the changes locally and verified that they work as expected.
- [x ]  I have followed the project's coding conventions and style guidelines.
- [ x]  I have rebased my branch onto the latest commit of the main branch.
- [x ]  I have performed a self-review of my own code.
- [x ]  I have read, understood …

Update export bookmarks endpoint to return file response

---

moonshot/__main__.py

This PR will check if user has node installed for their machine when installing moonshot-ui. And also allow for reinstallation of moonshot-data and moonshot-ui
<details>
```
Version 1.1
Everyone is permitted to …
```

[MS-396] Re-installation of MS-Data and UI and Check node requirement

---

.github/workflows/smoke-test.yaml

Change Pull Request Event to Pull Request Review Event
Allow Smoke Test to run only when merging to dev_main
Run Smoke Test in GitHub Actions
<details>
```
Version 1.1
By making a …
```

Change Pull Request Event to Pull Request Review Event

---

.github/workflows/smoke-test.yaml
.github/workflows/test-pypi-deployment.yaml

Remove Inputs for Workflow Dispatch For Test PyPi Deployment
Inputs are no longer needed for Work Workflow Dispatch For Test PyPi Deployment
Check that Inputs are no longer in Workflow Dispatch for Test PyPi Deployment Workflow
<details>
```
Version 1.1
license document, …
```

Remove Inputs for Workflow Dispatch For Test PyPi

---

moonshot/api.py
moonshot/src/api/api_dataset.py
tests/unit-tests/src/test_api_dataset.py

Removing this unuse api for now since benchmark augmentation is on hold. 
<details>
```
Version 1.1
Everyone is permitted to …
```

[MS-427][[BE] Dataset Converter Refactoring] - Remove Create Dataset API

---

tests/unit-tests/web_api/test_routes/test_routes_cookbook.py

Fix a unit test for test_routes_cookbook
Fix a unit test for test_routes_cookbook
A bug fix
1. Run `bash ci/run-test.sh` in root folder. All the unit tests should pass
<details>
```
Version 1.1
By making a contribution to this project, …
```

updated unit test

---

docs/faq.md

Update links to quick start and quick install guides
<details>
```
Version 1.1
Copyright (C) 2004, 2006 …
```

Update FAQ button click

---

moonshot/__main__.py

To support ms-621 by installing the spacy library required for entity processor in the setup process
To support ms-621 by installing the spacy model required for entity processor in the setup process
Installation of required model
Refer to https://github.com/aiverify-foundation/moonshot-data/pull/154
x
x
<details>
```
Version 1.1
By making a contribution to this project, I certify that:
(a) The contribution was …
```

[MS-621] Download Required Spacy Model for Entity Processor

---

docs/faq.md
docs/getting_started/quick_install.md

<details>
```
Version 1.1
Everyone …
```

Update faq for windows

---

moonshot/integrations/cli/__main__.py
moonshot/integrations/cli/redteam/session.py
moonshot/integrations/web_api/routes/benchmark_result.py
moonshot/integrations/web_api/routes/bookmark.py
moonshot/integrations/web_api/routes/context_strategy.py
moonshot/integrations/web_api/routes/prompt_template.py
moonshot/integrations/web_api/schemas/cookbook_create_dto.py
moonshot/integrations/web_api/schemas/prompt_response_model.py
moonshot/integrations/web_api/schemas/recipe_create_dto.py
moonshot/integrations/web_api/services/context_strategy_service.py
moonshot/integrations/web_api/services/cookbook_service.py
moonshot/integrations/web_api/services/session_service.py
moonshot/integrations/web_api/services/utils/exceptions_handler.py
moonshot/integrations/web_api/services/utils/results_formatter.py
moonshot/integrations/web_api/status_updater/interface/benchmark_progress_callback.py
moonshot/integrations/web_api/status_updater/interface/redteam_progress_callback.py
moonshot/src/cookbooks/cookbook_arguments.py
moonshot/src/redteaming/attack/attack_module.py

Fix linting issue
Fix linting issue
Routine tasks, maintenance, or tooling changes
Nothing to test manually. the pipeline will trigger the linting automatically
- x ]  I have followed the project's coding conventions and style guidelines.
<details>
```
Version 1.1 …
```

[MS-v0.6] Linting Issues for Moonshot Repo

---

README.md
moonshot/integrations/web_api/app.py
pyproject.toml

Update release version from 0.6.4 to 0.7.0.
- other: Other changes that don't fit into the above categories
Manual test in UAT and ran integration test.
- [ X ]  I have tested the changes locally and verified that they work as expected.
- [ X ]  I have followed the project's coding conventions and style guidelines.
- [ X ]  I have rebased my branch onto the latest commit of the main branch.
- [ X ]  I have performed a self-review of my own code. …

[WS-78][Release] Upgrade version from 0.6.4 to 0.7.0

---

docs/getting_started/quick_start.md

<details>
```
Version 1.1
Everyone …
```

Updating Quick start guide title

---

docs/components.md
docs/index.md
mkdocs.yml

Amend Index page and added Starter kit pages.
Other
<details>
```
Version 1.1
Everyone is permitted to copy and distribute …
```

Amend Index page and added Starter kit pages

---

docs/detailed_guide/run_benchmarks_UI.md
docs/detailed_guide/starter_kit_cookbooks.md

Fixed broken links in detailed guide sections
Fix broken links to improve user experience.
docs
<details>
```
Version 1.1
license document, but …
```

Fixed detailed guide sections

---

docs/detailed_guide/starter_kit_cookbooks.md
docs/getting_started/starter_kit.md

<details>
```
Version 1.1
Everyone …
```

Add hyperlink to starter_kit.md

---

README.md
moonshot/integrations/web_api/app.py
pyproject.toml

<details>
```
Version 1.1
Everyone …
```

[Release]Update versioning to 0.7.3
